### ISSUE TITLE
Compared With OpenIBL?

### ISSUE THREAD

**Issue by zhaihongjia** [goodproj13/DenserNet#3]
Your code is very similar to OpenIBL(https://github.com/yxgeee/OpenIBL), which is presented in ECCV2020. Why note compared with it.

**Comment by goodproj13** [comment]
Thanks for your interest. This project is under review of US patent. We should update the code periodically. The next release should be around 6/1/2021.

**Comment by scott-vsi** [comment]
I agree. The significant overlap in the content of this repository with OpenIBL at least deserves to be acknowledged.
