### ISSUE TITLE
DenserNet  model

### ISSUE THREAD

**Issue by ga1i13o** [goodproj13/DenserNet#4]
Hi,
the only place where I find an implementation of DenserNet is in Feature_branch.py. Anyway I am not able to understand how is the One-Stage Feature Decoder mentioned in paper implemented here; as I only see a fc layer on top of the feature branches that seems to be trained for classification and not for retrieval,
Can you give some indications in merit?

**Comment by goodproj13** [comment]
1. The full implementation is under review of the US patent. The disclosure is expected to be no later than the fall.
2. To perform one-stage feature decoder, use the descriptor and detector from "netvlad.py" and modify training, which now only uses the descriptor.
